spring.datasource.url=jdbc:sqlite:src/main/resources/doplus-database-test.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.data.jdbc.repositories.enabled=false

application.security.jwt.secret-key=C0EB29F733003F094A9756A05FA9688DC3BDCC78D581E226F12CFA3603420C50
application.security.jwt.expiration=86400000
